# Generated by Django 5.0.1 on 2024-02-22 11:03

import django.core.validators
import my_plant_app.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Username')),
                ('first_name', models.CharField(max_length=20, validators=[my_plant_app.profiles.validators.name_validator], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, validators=[my_plant_app.profiles.validators.name_validator], verbose_name='Last Name')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
            ],
        ),
    ]
