# Generated by Django 5.0.2 on 2024-02-22 06:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_name',
            field=models.CharField(max_length=30, verbose_name='Artist:'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('GENRE_POP', 'Pop Music'), ('GENRE_JAZZ', 'Jazz Music'), ('GENRE_R&B', 'R&B Music'), ('GENRE_ROCK', 'Rock Music'), ('GENRE_COUNTRY', 'Country Music'), ('GENRE_DANCE', 'Dance Music'), ('GENRE_HIP_HOP', 'Hip Hop Music'), ('GENRE_OTHER', 'Other')], max_length=30, verbose_name='Genre:'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(verbose_name='Image URL:'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Album name:'),
        ),
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price:'),
        ),
    ]
